{% set name = "catalystcoop.pudl" %}
{% set version = "2024.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4b75500770886284c974ec3dc1b54efa8199baa974508b61ce86c3029b96952b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - metadata_to_rst = pudl.convert.metadata_to_rst:main
    - epacems_to_parquet = pudl.convert.epacems_to_parquet:main
    - ferc_to_sqlite = pudl.ferc_to_sqlite.cli:main
    - pudl_datastore = pudl.workspace.datastore:main
    - pudl_etl = pudl.cli.etl:main
    - pudl_setup = pudl.workspace.setup_cli:main
    - state_demand = pudl.analysis.state_demand:main

requirements:
  host:
    - python >=3.8,<3.12
    - pip
    - setuptools_scm
  run:
    - python >=3.11,<3.12
    - addfips ==0.4.0
    - alembic ==1.12.1
    - boto3 ==1.33.5
    - bottleneck ==1.3.7
    - python-build ==1.0.3
    - catalystcoop.dbfread ==3.0.0
    - catalystcoop.ferc_xbrl_extractor ==1.3.1
    - click ==8.1.7
    - coloredlogs ==14.0
    - conda-lock ==2.5.1
    - coverage ==7.3.2
    - dagster ==1.5.9
    - dagster-postgres ==0.21.9
    - dask ==2023.11.0
    - datapackage ==1.15.2
    - datasette ==0.64.4
    - doc8 ==1.1.1
    - email-validator ==2.1.0
    - fsspec ==2023.10.0
    - furo ==2023.9.10
    - gcsfs ==2023.10.0
    - geopandas ==0.14.1
    - grpcio ==1.59.2
    - grpcio-health-checking ==1.59.2
    - grpcio-status ==1.59.2
    - hypothesis ==6.91.0
    - jinja2 ==3.1.2
    - jupyter
    - matplotlib-base ==3.8.2
    - nbconvert ==7.11.0
    - nbformat ==5.9.2
    - networkx ==3.2.1
    - numba ==0.58.1
    - numexpr ==2.8.7
    - numpy ==1.26.2
    - openpyxl ==3.1.2
    - pandas ==2.1.3
    - pandera ==0.17.2
    - pre-commit ==3.5.0
    - pyarrow ==14.0.1
    - pydantic ==2.5.2
    - pydantic-settings ==2.1.0
    - pytest ==7.4.3
    - pytest-cov ==4.1.0
    - pytest-console-scripts ==1.4.1
    - pytest-mock ==3.12.0
    - pytest-xdist ==3.5.0
    - python-dotenv ==1.0.0
    - pyxlsb ==1.0.10
    - pyyaml ==6.0.1
    - readthedocs-sphinx-ext ==2.2.3
    - recordlinkage ==0.16
    - responses ==0.24.1
    - ruff ==0.1.6
    - scikit-learn ==1.3.2
    - scipy ==1.11.4
    - Shapely ==2.0.2
    - sphinx-autoapi ==3.0.0
    - sphinx-issues ==1.2.0
    - sphinx-reredirects ==0.1.2
    - sphinx ==7.2.6
    - sphinxcontrib-bibtex ==2.6.1
    - sqlalchemy ==2.0.23
    - timezonefinder ==6.2.0
    - xlrd ==2.0.1
    - xlsxwriter ==3.1.9

test:
  imports:
    - pudl
  commands:
    - pudl_setup --help > /dev/null
    - metadata_to_rst --help > /dev/null
    - epacems_to_parquet --help > /dev/null
    - ferc_to_sqlite --help > /dev/null
    - pudl_datastore --help > /dev/null
    - pudl_etl --help > /dev/null
    - state_demand --help > /dev/null

about:
  home: https://catalyst.coop/pudl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open data processing pipeline for public US utility data.

  description: |
    The PUDL (Public Utility Data Liberation) project extracts electric
    utility data from US government sources, standardizes it, and integrates
    it for easier use by researchers, activists, journalists, and others
    working in the public interest. It includes data from EIA forms 860 and
    923, FERC form 1, EPA CEMS hourly, and other sources.

  doc_url: https://catalystcoop-pudl.readthedocs.io/
  dev_url: https://github.com/catalyst-cooperative/pudl

extra:
  recipe-maintainers:
    - zaneselvans
    - zschira
    - bendnorman
    - jdangerx
