{% set name = "catalystcoop.pudl" %}
{% set version = "2022.11.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 10c5c240b9f4a91f14782b67b266833e12d26a17ff9901a6d9bf905eadd7d0a8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - censusdp1tract_to_sqlite = pudl.convert.censusdp1tract_to_sqlite:main
    - metadata_to_rst = pudl.convert.metadata_to_rst:main
    - epacems_to_parquet = pudl.convert.epacems_to_parquet:main
    - ferc1_to_sqlite = pudl.convert.ferc1_to_sqlite:main
    - pudl_datastore = pudl.workspace.datastore:main
    - pudl_etl = pudl.cli:main
    - pudl_setup = pudl.workspace.setup_cli:main
    - state_demand = pudl.analysis.state_demand:main

requirements:
  host:
    - python >=3.8,<3.11
    - pip
    - setuptools_scm
  run:
    - python >=3.10,<3.11
    - addfips >=0.4,<0.5
    - catalystcoop.dbfread >=3.0,<3.1
    - catalystcoop.ferc-xbrl-extractor ==0.6.1
    - coloredlogs >=15.0,<15.1
    - dask >=2021.8,<2022.11.2
    - datapackage >=1.11,<1.16
    - email-validator >=1.0.3  # pydantic email extra
    - fsspec >=2021.7,<2022.11.1
    - gcsfs >=2021.7,<2022.11.1
    - geopandas >=0.9,<0.13
    - jinja2 >=2,<3.2
    - matplotlib-base >=3.3,<3.7
    - networkx >=2.2,<2.9
    - numpy >=1.18.5,<1.24,!=1.23.0
    - pandas >=1.4,<1.5.3
    - pyarrow >=5,<10.1
    - pydantic >=1.7,<2
    - pygeos >=0.10,<0.14
    - python-snappy >=0.6,<0.7
    - pyyaml >=5,<6.1
    - scikit-learn >=1.0,<1.2
    - scipy >=1.6,<1.10
    - shapely >1.8.0,!=1.8.3,<2.1
    - sqlalchemy >=1.4,<1.4.45
    - sqlite >=3.36,<4
    - timezonefinder >=5,<6.2
    - xlsxwriter >=3,<3.1

test:
  imports:
    - pudl
  commands:
    - pudl_setup --clobber
    - censusdp1tract_to_sqlite --help > /dev/null
    - epacems_to_parquet --help > /dev/null
    - ferc_to_sqlite --help > /dev/null
    - metadata_to_rst --help > /dev/null
    - metadata_to_yml --help > /dev/null
    - pudl_datastore --help > /dev/null
    - pudl_etl --help > /dev/null
    - state_demand --help > /dev/null

about:
  home: https://catalyst.coop/pudl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open data processing pipeline for public US utility data.

  description: |
    The PUDL (Public Utility Data Liberation) project extracts electric
    utility data from US government sources, standardizes it, and integrates
    it for easier use by researchers, activists, journalists, and others
    working in the public interest. It includes data from EIA forms 860 and
    923, FERC form 1, EPA CEMS hourly, and other sources.

  doc_url: https://catalystcoop-pudl.readthedocs.io/
  dev_url: https://github.com/catalyst-cooperative/pudl

extra:
  recipe-maintainers:
    - zaneselvans
    - zschira
    - bendnorman
