{% set name = "catalystcoop.pudl" %}
{% set pypi_normalized_name = "catalystcoop_pudl" %}
{% set version = "2025.7.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ pypi_normalized_name }}/{{ pypi_normalized_name }}-{{ version }}.tar.gz
  sha256: 79bcea2813cac7b3f3b66f0227e136dd3c3d025b8a498d5f63efe800def49416
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dbt_helper = pudl.scripts.dbt_helper:dbt_helper
    - ferc_to_sqlite = pudl.ferc_to_sqlite.cli:main
    - metadata_to_rst = pudl.convert.metadata_to_rst:metadata_to_rst
    - pudl_check_fks = pudl.etl.check_foreign_keys:pudl_check_fks
    - pudl_datastore = pudl.workspace.datastore:pudl_datastore
    - pudl_etl = pudl.etl.cli:pudl_etl
    - pudl_service_territories = pudl.analysis.service_territory:pudl_service_territories

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }},<3.13
    - alembic ==1.16.2
    - boto3 ==1.38.27
    - bottleneck ==1.5.0
    - catalystcoop.dbfread ==3.0.0
    - catalystcoop.ferc_xbrl_extractor ==1.6.0
    - click ==8.1.8
    - coloredlogs ==14.0
    - conda-lock ==3.0.3
    - coverage ==7.9.1
    - dagster ==1.11.0
    - dagster-dbt ==1!0.27.0
    - dagster-postgres ==1!0.27.0
    - dask-core ==2025.5.1
    - dask-expr ==2.0.0
    - datasette ==0.65.1
    - dbt-duckdb ==1.9.2
    - deepdiff ==7.0.1
    - doc8 ==2.0.0
    - email_validator ==2.2.0
    - frictionless ==5.18.1
    - fsspec ==2025.5.1
    - furo ==2024.8.6
    - gcsfs ==2025.5.1
    - gdal ==3.11.0
    - geopandas ==1.1.1
    - grpcio ==1.71.0
    - grpcio-health-checking ==1.71.0
    - grpcio-status ==1.71.0
    - hypothesis ==6.135.17
    - jellyfish ==1.1.3
    - jinja2 ==3.1.6
    - jupyter ==1.1.1
    - matplotlib-base ==3.10.3
    - mlflow ==3.1.1
    - nbconvert ==7.16.6
    - nbformat ==5.10.4
    - networkx ==3.5
    - numba ==0.61.2
    - numexpr ==2.10.2
    - numpy ==2.2.6
    - packaging ==24.2
    - pandas ==2.3.0
    - pandera-core ==0.23.1
    - pre-commit ==4.2.0
    - pyarrow ==19.0.1
    - pydantic ==2.11.7
    - pydantic-settings ==2.10.1
    - pytest ==8.4.1
    - pytest-console-scripts ==1.4.1
    - pytest-cov ==6.2.1
    - pytest-mock ==3.14.1
    - pytest-xdist ==3.7.0
    - python-build ==1.2.2.post1
    - python-calamine ==0.3.2
    - python-dotenv ==1.1.1
    - python-duckdb ==1.3.1
    - pytz ==2025.2
    - pyyaml ==6.0.2
    - readthedocs-sphinx-ext ==2.2.5
    - requests ==2.32.4
    - responses ==0.25.7
    - ruff ==0.12.1
    - s3fs ==2025.5.1
    - scikit-learn ==1.7.0
    - scipy ==1.16.0
    - shapely ==2.1.1
    - sphinx ==8.2.3
    - sphinx-autoapi ==3.5.0
    - sphinx-issues ==5.0.1
    - sphinx-reredirects ==1.0.0
    - sphinxcontrib-bibtex ==2.6.5
    - sphinxcontrib-googleanalytics ==0.5
    - splink ==4.0.8
    - sqlalchemy ==2.0.41
    - sqlglot ==26.30.0
    - timezonefinder ==6.5.9
    - typos ==1.33.1
    - universal_pathlib ==0.2.6
    - urllib3 ==2.5.0
    - xlsxwriter ==3.2.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - pudl
  commands:
    - dbt_helper --help > /dev/null
    - ferc_to_sqlite --help > /dev/null
    - metadata_to_rst --help > /dev/null
    - pudl_check_fks --help > /dev/null
    - pudl_datastore --help > /dev/null
    - pudl_etl --help > /dev/null
    - pudl_service_territories --help > /dev/null

about:
  home: https://catalyst.coop/pudl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open data processing pipeline for public US utility data.

  description: |
    The PUDL (Public Utility Data Liberation) project extracts electric
    utility data from US government sources, standardizes it, and integrates
    it for easier use by researchers, activists, journalists, and others
    working in the public interest. It includes data from EIA forms 860 and
    923, FERC form 1, EPA CEMS hourly, and other sources.

  doc_url: https://catalystcoop-pudl.readthedocs.io/
  dev_url: https://github.com/catalyst-cooperative/pudl

extra:
  recipe-maintainers:
    - marianneke
    - zaneselvans
    - zschira
    - jdangerx
