{% set name = "catalystcoop.pudl" %}
{% set pypi_normalized_name = "catalystcoop_pudl" %}
{% set version = "2025.5.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ pypi_normalized_name }}/{{ pypi_normalized_name }}-{{ version }}.tar.gz
  sha256: 6a1dd33f716c9cfae0505eeea567bd86fb0fa524f15aa6f51023bbaf7f066e05
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dbt_helper = pudl.scripts.dbt_helper:dbt_helper
    - ferc_to_sqlite = pudl.ferc_to_sqlite.cli:main
    - metadata_to_rst = pudl.convert.metadata_to_rst:metadata_to_rst
    - pudl_check_fks = pudl.etl.check_foreign_keys:pudl_check_fks
    - pudl_datastore = pudl.workspace.datastore:pudl_datastore
    - pudl_etl = pudl.etl.cli:pudl_etl
    - pudl_service_territories = pudl.analysis.service_territory:pudl_service_territories

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }},<3.13
    - addfips ==0.4.2
    - alembic ==1.14.1
    - boto3 ==1.36.16
    - bottleneck ==1.4.2
    - catalystcoop.dbfread ==3.0.0
    - catalystcoop.ferc_xbrl_extractor ==1.5.1
    - click ==8.1.8
    - coloredlogs ==14.0
    - conda-lock ==2.5.7
    - coverage ==7.6.11
    - dagster ==1.9.11
    - dagster-postgres ==0.25.11
    - dask ==2025.1.0
    - dask-expr ==2.0.0
    - datasette ==0.65.1
    - doc8 ==1.1.2
    - email-validator ==2.2.0
    - frictionless ==5.18.0
    - fsspec ==2025.2.0
    - furo ==2024.8.6
    - gcsfs ==2025.2.0
    - gdal ==3.10.1
    - geopandas ==1.0.1
    - grpcio ==1.67.1
    - grpcio-health-checking ==1.67.1
    - grpcio-status ==1.67.1
    - hypothesis ==6.125.1
    - jellyfish ==1.1.3
    - jinja2 ==3.1.5
    - jupyter
    - matplotlib-base ==3.10.0
    - mlflow ==2.20.1
    - nbconvert ==7.16.6
    - nbformat ==5.10.4
    - networkx ==3.4.2
    - numba ==0.61.0
    - numexpr ==2.10.2
    - numpy ==2.1.3
    - openpyxl ==3.1.5
    - packaging ==24.2
    - pandas ==2.2.3
    - pandera ==0.22.1
    - pre-commit ==4.1.0
    - pyarrow ==18.1.0
    - pydantic ==2.10.6
    - pydantic-settings ==2.7.1
    - pytest ==8.3.4
    - pytest-console-scripts ==1.4.1
    - pytest-cov ==6.0.0
    - pytest-mock ==3.14.0
    - pytest-xdist ==3.6.1
    - python-build ==1.2.2.post1
    - python-calamine ==0.3.1
    - python-dotenv ==1.0.1
    - pytz ==2024.1
    - pyyaml ==6.0.2
    - readthedocs-sphinx-ext ==2.2.5
    - requests ==2.32.3
    - responses ==0.25.6
    - ruff ==0.9.5
    - scikit-learn ==1.6.1
    - scipy ==1.15.1
    - shapely ==2.0.7
    - splink ==4.0.6
    - sphinx ==8.1.3
    - sphinx-autoapi ==3.4.0
    - sphinx-issues ==5.0.0
    - sphinx-reredirects ==0.1.5
    - sphinxcontrib-bibtex ==2.6.3
    - sphinxcontrib-googleanalytics ==0.4
    - sqlalchemy ==2.0.38
    - sqlglot ==26.0.1
    - sqlite ==3.48.0
    - timezonefinder ==6.5.8
    - universal_pathlib ==0.2.6
    - urllib3 ==1.26.19
    - xlsxwriter ==3.2.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - pudl
  commands:
    - dbt_helper --help > /dev/null
    - ferc_to_sqlite --help > /dev/null
    - metadata_to_rst --help > /dev/null
    - pudl_check_fks --help > /dev/null
    - pudl_datastore --help > /dev/null
    - pudl_etl --help > /dev/null
    - pudl_service_territories --help > /dev/null

about:
  home: https://catalyst.coop/pudl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open data processing pipeline for public US utility data.

  description: |
    The PUDL (Public Utility Data Liberation) project extracts electric
    utility data from US government sources, standardizes it, and integrates
    it for easier use by researchers, activists, journalists, and others
    working in the public interest. It includes data from EIA forms 860 and
    923, FERC form 1, EPA CEMS hourly, and other sources.

  doc_url: https://catalystcoop-pudl.readthedocs.io/
  dev_url: https://github.com/catalyst-cooperative/pudl

extra:
  recipe-maintainers:
    - zaneselvans
    - zschira
    - jdangerx
