{% set name = "catalystcoop.pudl" %}
{% set pypi_normalized_name = "catalystcoop_pudl" %}
{% set version = "2024.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ pypi_normalized_name }}/{{ pypi_normalized_name }}-{{ version }}.tar.gz
  sha256: 3ee08112480a17e7987ce359e15fd938302d9aa0c9e9d00a6402b9ab19b40f8b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ferc_to_sqlite = pudl.ferc_to_sqlite.cli:main
    - metadata_to_rst = pudl.convert.metadata_to_rst:metadata_to_rst
    - pudl_check_fks = pudl.etl.check_foreign_keys:pudl_check_fks
    - pudl_datastore = pudl.workspace.datastore:pudl_datastore
    - pudl_etl = pudl.etl.cli:pudl_etl
    - pudl_service_territories = pudl.analysis.service_territory:pudl_service_territories

requirements:
  host:
    - python >=3.8,<3.13
    - pip
    - setuptools_scm
  run:
    - python >=3.12,<3.13
    - addfips ==0.4.0
    - alembic ==1.13.1
    - boto3 ==1.34.108
    - bottleneck ==1.3.8
    - catalystcoop.dbfread ==3.0.0
    - catalystcoop.ferc_xbrl_extractor ==1.4.0
    - click ==8.1.7
    - coloredlogs ==14.0
    - conda-lock ==2.5.7
    - coverage ==7.5.1
    - dagster ==1.7.6
    - dagster-postgres ==0.23.6
    - dask ==2024.5.1
    - datasette ==0.64.6
    - doc8 ==1.1.1
    - email-validator ==2.1.1
    - frictionless ==5.16.1
    - fsspec ==2024.5.0
    - furo ==2024.5.6
    - gcsfs ==2024.5.0
    - gdal ==3.8.5
    - geopandas ==0.14.4
    - grpcio ==1.62.2
    - grpcio-health-checking ==1.62.2
    - grpcio-status ==1.62.2
    - hypothesis ==6.102.4
    - jellyfish ==1.0.3
    - jinja2 ==3.1.4
    - jupyter
    - matplotlib-base ==3.8.4
    - mlflow ==2.12.2
    - nbconvert ==7.16.4
    - nbformat ==5.10.4
    - networkx ==3.3
    - numba ==0.59.1
    - numexpr ==2.9.0
    - numpy ==1.26.4
    - openpyxl ==3.1.2
    - packaging ==24.0
    - pandas ==2.2.2
    - pandera ==0.19.1
    - pre-commit ==3.7.1
    - pyarrow ==15.0.2
    - pydantic ==2.7.1
    - pydantic-settings ==2.2.1
    - pytest ==8.2.0
    - pytest-cov ==5.0.0
    - pytest-console-scripts ==1.4.1
    - pytest-mock ==3.14.0
    - pytest-xdist ==3.5.0
    - python-build ==1.2.1
    - python-calamine ==0.2.0
    - python-dotenv ==1.0.1
    - pytz ==2024.1
    - pyyaml ==6.0.1
    - readthedocs-sphinx-ext ==2.2.5
    - requests ==2.31.0
    - responses ==0.25.0
    - ruff ==0.4.4
    - scikit-learn ==1.4.2
    - scipy ==1.13.0
    - Shapely ==2.0.4
    - splink ==3.9.14
    - sphinx ==7.3.7
    - sphinx-autoapi ==3.0.0
    - sphinx-issues ==1.2.0
    - sphinx-reredirects ==0.1.2
    - sphinxcontrib-bibtex ==2.6.2
    - sqlalchemy ==2.0.30
    - sqlglot ==23.17.0
    - sqlite ==3.45.3
    - timezonefinder ==6.4.1
    - universal_pathlib ==0.2.2
    - urllib3 ==1.26.18
    - xlsxwriter ==3.1.9

test:
  imports:
    - pudl
  commands:
    - ferc_to_sqlite --help > /dev/null
    - metadata_to_rst --help > /dev/null
    - pudl_check_fks --help > /dev/null
    - pudl_datastore --help > /dev/null
    - pudl_etl --help > /dev/null
    - pudl_service_territories --help > /dev/null

about:
  home: https://catalyst.coop/pudl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open data processing pipeline for public US utility data.

  description: |
    The PUDL (Public Utility Data Liberation) project extracts electric
    utility data from US government sources, standardizes it, and integrates
    it for easier use by researchers, activists, journalists, and others
    working in the public interest. It includes data from EIA forms 860 and
    923, FERC form 1, EPA CEMS hourly, and other sources.

  doc_url: https://catalystcoop-pudl.readthedocs.io/
  dev_url: https://github.com/catalyst-cooperative/pudl

extra:
  recipe-maintainers:
    - zaneselvans
    - zschira
    - bendnorman
    - jdangerx
